### ISSUE TITLE
Vanilla 1.14 performance issues

### ISSUE THREAD

**Issue by michaelblight** [itzg/dockerfiles#311]
Everything was running fine until the upgrade to 1.14 and now I'm getting chunks loading very slowly, rubber-banding and timeout issues. Anybody else? I'm running the vanilla version with no mods on a Windows box under a Virtualbox Ubuntu VM. I've upped the VM and Minecraft RAM to 3GB and allowed it to use 100% of all 4 cores (admittedly older 3rd gen i7 though). Currently pretty unplayable. Help!

**Comment by itzg** [comment]
I was going to bump up some of my containers to 1.14, so I'll see what it does for me too.

**Comment by itzg** [comment]
I have pushed an update to the image that upgrades the base image to the latest Java 8 version. I'm hoping that helps your scenario. 

The startup time is definitely longer with 1.14, but it was eventually playable. For reference I tried it on Docker for Desktop on Windows with the VM set at 2GB Memory with 2 vCPUs.

**Comment by michaelblight** [comment]
Still no joy. I created a new VM and on starting Minecraft with the new image I immediately got "Is the server overloaded" messages even though nobody was connected. Soon after I connected, the server logged "a single server tick took 60.0 seconds" so it considered itself crashed and did a shutdown. I setup another VM with Minecraft (not in Docker) and it ran somewhat better, but still not as well as 1.13. This at least shows it's not a bug in the image. Tomorrow I will try moving it all to an SSD to see if that helps.

**Comment by SirPole** [comment]
Hey! I've just set up my server on **1.14** and can report the same issue. Constant load of about 15%, **1.13.2** on the other hand uses only 2%... I'm guessing this is minecraft issue and we'll have to wait for a fix...

**Comment by michaelblight** [comment]
So it seems it's a known issue with 1.14 ... https://bugs.mojang.com/browse/MC-149178

**Comment by itzg** [comment]
@michaelblight , in that case, do you mind if we close the issue here since it is not specific to the containerization?
